# Generated by Django 3.2.5 on 2021-08-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210820_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_title',
        ),
    ]
