# Generated by Django 3.2.5 on 2021-08-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=12)),
                ('age', models.CharField(max_length=12)),
                ('id_Number', models.CharField(max_length=12)),
                ('phone_number', models.PositiveIntegerField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('profession', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=10)),
                ('lessons_per_month', models.PositiveSmallIntegerField(max_length=3)),
                ('syllabus', models.FileField(upload_to='')),
                ('contract', models.FileField(upload_to='')),
                ('bank_account', models.CharField(max_length=16)),
                ('resume', models.FileField(upload_to='')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
