# Generated by Django 3.2.5 on 2021-08-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='lessons_per_month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
