# Generated by Django 3.2.5 on 2021-08-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_auto_20210820_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='id_Number',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='course',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='course_code',
            new_name='unit_code',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gender',
            field=models.CharField(choices=[('=M', 'Male'), ('K', 'Female'), ('O', 'Other')], max_length=20),
        ),
    ]
