# Generated by Django 3.2.5 on 2021-08-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_id', models.CharField(blank=True, max_length=20, null=True)),
                ('event_date', models.DateTimeField()),
                ('event_agenda', models.CharField(blank=True, max_length=30, null=True)),
                ('event_venue', models.CharField(blank=True, max_length=10, null=True)),
                ('event_duration', models.DurationField(blank=True, null=True)),
                ('number_of_event_attendees', models.BigIntegerField()),
                ('event_planner', models.CharField(blank=True, max_length=10, null=True)),
                ('event_activity', models.CharField(blank=True, max_length=10, null=True)),
                ('event_approved_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
