# Generated by Django 3.2.5 on 2021-07-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=10)),
                ('Last_name', models.CharField(max_length=10)),
                ('Age', models.PositiveSmallIntegerField()),
                ('Date_of_birth', models.DateField()),
                ('Gender', models.CharField(choices=[('=M', 'Male'), ('K', 'Female'), ('O', 'Other')], max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Languages', models.CharField(choices=[('E', 'English'), ('K', 'Kiswahili'), ('O', 'Other')], max_length=2)),
                ('ID_number', models.CharField(max_length=10)),
                ('Nationality', models.CharField(max_length=20)),
                ('Passport_photo', models.ImageField(upload_to='')),
                ('Phone_number', models.PositiveIntegerField()),
                ('Room_number', models.PositiveSmallIntegerField()),
                ('Mentors_name', models.CharField(max_length=20)),
                ('Class_name', models.CharField(max_length=10)),
                ('Medical_report', models.FileField(upload_to='')),
                ('Laptop_serial', models.CharField(max_length=10)),
                ('Big_sister', models.CharField(max_length=20)),
                ('Passport_number', models.CharField(max_length=10)),
                ('Guardian', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
            ],
        ),
    ]
