# Generated by Django 3.2.5 on 2021-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Nationality',
            field=models.CharField(choices=[('=M', 'Kenya'), ('K', 'Uganda'), ('O', 'Sudan')], max_length=20),
        ),
    ]
